use criterion::{black_box, criterion_group, criterion_main, Criterion};
use learn_pltl_fast::*;
use std::fs::File;
use std::io::prelude::*;
use std::io::BufReader;

fn solve_sample(c: &mut Criterion) {
    // let file = File::open("sample_0197.ron").expect("open sample file");
    let file = File::open("sample_(G(¬(x0)))∨(F((x0)∧(F(x1)))).ron").expect("open sample file");
    let mut buf_reader = BufReader::new(file);
    let mut contents = Vec::new();
    buf_reader
        .read_to_end(&mut contents)
        .expect("read sample file");
    let sample: Sample<2> = ron::de::from_bytes(&contents).expect("deserialize sample");

    // c.bench_function("solve sample", |b| {
    //     b.iter(|| par_brute_solve(black_box(&sample), false))
    // });

    // let sample = one_three_0077();

    c.bench_function("solve sample 0077", |b| {
        b.iter(|| brute_solve(black_box(&sample), false))
    });

    c.bench_function("solve sample 0077, par", |b| {
        b.iter(|| par_brute_solve(black_box(&sample), false))
    });
}

criterion_group!(benches, solve_sample);
criterion_main!(benches);

// pub fn load_and_solve(contents: Vec<u8>) -> Option<String> {
//     // Ugly hack to get around limitations of deserialization for types with const generics.
//     (1..=5)
//         .into_iter()
//         .find_map(|n| {
//             match n {
//                 1 => ron::de::from_bytes::<Sample<1>>(&contents)
//                     .map(|sample| par_brute_solve(&sample, true)),
//                 2 => ron::de::from_bytes::<Sample<2>>(&contents)
//                     .map(|sample| par_brute_solve(&sample, true)),
//                 3 => ron::de::from_bytes::<Sample<3>>(&contents)
//                     .map(|sample| par_brute_solve(&sample, true)),
//                 4 => ron::de::from_bytes::<Sample<4>>(&contents)
//                     .map(|sample| par_brute_solve(&sample, true)),
//                 5 => ron::de::from_bytes::<Sample<5>>(&contents)
//                     .map(|sample| par_brute_solve(&sample, true)),
//                 _ => panic!("out-of-bound parameter"),
//             }
//             .ok()
//             .flatten()
//         })
//         // .map(|arc| (*arc).clone())
// }

pub fn one_three_0077() -> Sample<3> {
    Sample {
        positive_traces: vec![
            vec![
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [true, true, false],
                [true, true, true],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, true, false],
                [false, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [false, true, false],
                [false, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [true, true, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, true, true],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
            ],
            vec![
                [true, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, true, false],
                [false, false, true],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, true, true],
            ],
            vec![
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [true, false, false],
                [true, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
            ],
            vec![
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [true, false, false],
                [false, true, false],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
            ],
            vec![
                [false, false, false],
                [true, true, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [true, true, true],
                [false, false, true],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, false],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, true, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            vec![
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
            ],
            vec![
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [false, false, true],
            ],
        ],
        negative_traces: vec![
            vec![
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
            ],
            vec![
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
            ],
        ],
    }
}
