use criterion::{black_box, criterion_group, criterion_main, Criterion};
use learn_pltl_fast::*;

use std::fs::File;
use std::io::prelude::*;
use std::io::BufReader;

fn solve_sample(c: &mut Criterion) {
    // let sample = one_three_0077();

    let file = File::open("_sample_0077.ron").expect("open file");
    let mut buf_reader = BufReader::new(file);
    let mut contents = Vec::new();
    buf_reader.read_to_end(&mut contents).expect("read");
    let sample = ron::de::from_bytes::<Sample<3>>(&contents).expect("sample");

    c.bench_function("solve sample 0077", |b| {
        b.iter(|| par_brute_solve(black_box(&sample), false))
    });

    let file = File::open("_sample_0197.ron").expect("open file");
    let mut buf_reader = BufReader::new(file);
    let mut contents = Vec::new();
    buf_reader.read_to_end(&mut contents).expect("read");
    let sample = ron::de::from_bytes::<Sample<3>>(&contents).expect("sample");

    c.bench_function("solve sample 0197", |b| {
        b.iter(|| par_brute_solve(black_box(&sample), false))
    });

    let file = File::open("_sample_tbth0000.ron").expect("open file");
    let mut buf_reader = BufReader::new(file);
    let mut contents = Vec::new();
    buf_reader.read_to_end(&mut contents).expect("read");
    let sample = ron::de::from_bytes::<Sample<3>>(&contents).expect("sample");

    c.bench_function("solve sample tbth 0000", |b| {
        b.iter(|| par_brute_solve(black_box(&sample), false))
    });
}

criterion_group!(benches, solve_sample);
criterion_main!(benches);

// pub fn one_three_0077() -> Sample<3> {
//     Sample {
//         positive_traces: vec![
//             vec![
//                 [false, false, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [false, true, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, true, true],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, true, true],
//                 [false, true, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, true, false],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, true, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, true, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, true, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, false],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, true, false],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, true, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, true, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, true, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, true, false],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [false, true, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, true, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, true, true],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, true, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, true, false],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, true, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, true, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, true, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, true, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, true, false],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, true, true],
//                 [false, false, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, true, false],
//                 [true, false, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, true, false],
//                 [false, true, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, false],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, true, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, true, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [true, true, false],
//                 [false, true, true],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [true, true, true],
//                 [false, true, true],
//                 [true, true, true],
//                 [true, true, true],
//                 [false, false, true],
//                 [false, true, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, true, true],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, true, true],
//                 [false, false, true],
//                 [false, true, true],
//                 [true, false, false],
//                 [true, true, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, true, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, true, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, true, false],
//                 [false, false, true],
//             ],
//         ],
//         negative_traces: vec![
//             vec![
//                 [false, true, true],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, true, false],
//                 [false, false, true],
//                 [false, true, false],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, false],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, true, true],
//                 [false, true, true],
//                 [false, false, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, false, false],
//                 [false, false, false],
//                 [false, false, false],
//                 [true, false, true],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [true, false, true],
//                 [true, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, true],
//             ],
//             vec![
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [false, false, true],
//                 [true, false, false],
//                 [true, false, false],
//                 [false, false, false],
//                 [true, false, true],
//             ],
//             vec![
//                 [false, true, true],
//                 [false, true, false],
//                 [false, true, false],
//                 [true, false, true],
//                 [false, false, false],
//                 [true, false, false],
//                 [false, false, true],
//                 [false, false, true],
//                 [false, false, false],
//                 [false, false, true],
//             ],
//         ],
//     }
// }
