use criterion::{black_box, criterion_group, criterion_main, Criterion};
use learn_pltl_fast::*;

fn solve_sample(c: &mut Criterion) {
    let sample = one_three_0077();

    c.bench_function("solve sample 0077", |b| {
        b.iter(|| brute_solve(black_box(&sample), false))
    });

    c.bench_function("solve sample 0077, par", |b| {
        b.iter(|| par_brute_solve(black_box(&sample), false))
    });
}

criterion_group!(benches, solve_sample);
criterion_main!(benches);

pub fn one_three_0077() -> Sample<3> {
    Sample {
        positive_traces: vec![
            vec![
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [true, true, false],
                [true, true, true],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, true, false],
                [false, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [false, true, false],
                [false, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [true, true, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, true, true],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
            ],
            vec![
                [true, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, true, false],
                [false, false, true],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, true, true],
            ],
            vec![
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [true, false, false],
                [true, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            vec![
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            vec![
                [false, true, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
            ],
            vec![
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [true, false, false],
                [false, true, false],
            ],
            vec![
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
            ],
            vec![
                [false, false, false],
                [true, true, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [true, true, true],
                [false, false, true],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, true, true],
            ],
            vec![
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
            ],
            vec![
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, false],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, true],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, true, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            vec![
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, true],
            ],
            vec![
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
            ],
            vec![
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            vec![
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, false],
            ],
            vec![
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            vec![
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, true, false],
            ],
            vec![
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
            ],
            vec![
                [true, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
            ],
            vec![
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
            ],
            vec![
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [false, false, true],
            ],
        ],
        negative_traces: vec![
            vec![
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
            ],
            vec![
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
            ],
            vec![
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [true, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
            ],
            vec![
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
            ],
            vec![
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
            ],
            vec![
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
            ],
            vec![
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            vec![
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
            ],
            vec![
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            vec![
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
            ],
            vec![
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
            ],
        ],
    }
}
