mod de_sample;
mod learn;
mod syntax;
mod trace;

pub use de_sample::*;
pub use learn::*;
pub use syntax::*;
pub use trace::*;

pub fn one_three_0077<'a>() -> Sample<'a, 3> {
    Sample {
        positive_traces: vec![
            &[
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            &[
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [false, false, false],
            ],
            &[
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            &[
                [false, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, true],
            ],
            &[
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            &[
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, true, true],
            ],
            &[
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            &[
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            &[
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [true, true, false],
                [true, true, true],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, true, false],
                [false, true, true],
            ],
            &[
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            &[
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [true, false, false],
            ],
            &[
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
            ],
            &[
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [false, true, false],
                [false, false, true],
            ],
            &[
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            &[
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
            ],
            &[
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [true, true, false],
            ],
            &[
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
            ],
            &[
                [false, true, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            &[
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, true, true],
                [false, true, true],
                [true, false, false],
            ],
            &[
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            &[
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [true, true, true],
            ],
            &[
                [true, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, true],
            ],
            &[
                [false, false, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [false, false, true],
                [true, true, false],
            ],
            &[
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
            ],
            &[
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, true],
            ],
            &[
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
            ],
            &[
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            &[
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            &[
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, false],
            ],
            &[
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
            ],
            &[
                [true, true, false],
                [true, true, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, false, false],
                [false, false, true],
            ],
            &[
                [false, true, true],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, true, false],
                [false, false, true],
            ],
            &[
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, true],
            ],
            &[
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            &[
                [false, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            &[
                [false, false, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [true, false, false],
            ],
            &[
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, true, true],
            ],
            &[
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [false, true, true],
            ],
            &[
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
            ],
            &[
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
            ],
            &[
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            &[
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            &[
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, true],
            ],
            &[
                [true, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
            ],
            &[
                [true, true, true],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [true, true, true],
            ],
            &[
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [true, true, true],
            ],
            &[
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
            ],
            &[
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, true, true],
            ],
            &[
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, true, false],
                [true, true, true],
            ],
            &[
                [true, false, false],
                [true, true, false],
                [true, false, true],
                [true, true, true],
                [true, false, true],
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
            ],
            &[
                [true, true, true],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
                [false, true, false],
            ],
            &[
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
            ],
            &[
                [true, true, true],
                [true, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            &[
                [true, true, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            &[
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            &[
                [false, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
            ],
            &[
                [false, false, true],
                [false, true, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
            ],
            &[
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
            ],
            &[
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
            ],
            &[
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [false, false, false],
            ],
            &[
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [true, false, true],
            ],
            &[
                [true, false, true],
                [true, false, false],
                [true, true, false],
                [true, false, false],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
            ],
            &[
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            &[
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, true],
            ],
            &[
                [false, false, true],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, true],
                [false, false, false],
            ],
            &[
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
            ],
            &[
                [false, false, true],
                [true, false, true],
                [true, false, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, false, false],
            ],
            &[
                [true, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, true, false],
            ],
            &[
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, false],
            ],
            &[
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
                [false, false, true],
                [true, true, true],
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, false],
            ],
            &[
                [false, false, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [false, false, false],
            ],
            &[
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, true],
            ],
            &[
                [true, false, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [true, true, true],
            ],
            &[
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, false, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, false, true],
            ],
            &[
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, true],
            ],
            &[
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            &[
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [true, false, false],
            ],
            &[
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            &[
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, false, false],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, false],
                [true, true, false],
            ],
            &[
                [false, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, false, true],
            ],
            &[
                [true, false, false],
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, false],
                [true, false, false],
            ],
            &[
                [false, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
            ],
            &[
                [false, true, true],
                [true, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [false, true, true],
            ],
            &[
                [false, false, false],
                [false, true, false],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
                [false, true, false],
                [false, true, false],
            ],
            &[
                [false, true, true],
                [false, false, true],
                [true, true, true],
                [false, false, false],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, true, true],
                [false, false, true],
            ],
            &[
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [true, true, false],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, true],
            ],
            &[
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
                [false, false, true],
                [true, true, true],
            ],
            &[
                [false, false, false],
                [true, true, false],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, true],
                [false, true, true],
                [false, false, false],
            ],
            &[
                [false, false, true],
                [false, true, true],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, true],
                [true, false, true],
                [true, false, false],
            ],
            &[
                [true, false, true],
                [true, true, true],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            &[
                [false, false, true],
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [false, false, true],
                [true, true, false],
                [true, true, false],
            ],
            &[
                [false, true, true],
                [true, false, false],
                [true, false, false],
                [false, true, true],
                [true, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, true, true],
                [true, false, false],
            ],
            &[
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, true],
                [true, false, false],
                [false, true, false],
            ],
            &[
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, true],
                [true, true, true],
                [true, false, true],
                [false, true, false],
            ],
            &[
                [false, false, false],
                [true, true, true],
                [false, true, true],
                [true, false, true],
                [true, true, true],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            &[
                [false, false, true],
                [false, true, false],
                [true, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            &[
                [true, true, true],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, true],
                [false, false, true],
                [false, false, true],
                [true, true, false],
                [true, false, false],
            ],
            &[
                [false, true, false],
                [false, false, true],
                [true, true, true],
                [false, false, true],
                [true, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            &[
                [false, false, true],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, false, true],
                [true, true, false],
                [false, true, false],
                [true, true, true],
            ],
            &[
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, true, false],
            ],
            &[
                [true, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, false],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, true, true],
            ],
            &[
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, true, false],
                [true, true, true],
                [false, true, false],
                [true, false, false],
            ],
            &[
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, true, true],
                [false, true, true],
                [false, true, true],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, true, false],
                [true, true, false],
            ],
            &[
                [true, true, true],
                [false, false, false],
                [true, false, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, true, false],
                [false, false, false],
                [true, true, true],
                [true, true, true],
            ],
            &[
                [true, true, true],
                [true, true, false],
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [false, true, true],
                [false, false, false],
            ],
            &[
                [true, false, false],
                [true, true, false],
                [true, true, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [false, false, false],
            ],
            &[
                [false, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [false, true, false],
                [true, true, false],
                [true, true, false],
            ],
            &[
                [true, true, false],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [false, true, false],
                [true, true, true],
                [false, false, false],
                [true, true, false],
            ],
            &[
                [false, false, false],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, true, false],
                [true, false, false],
                [true, true, false],
                [false, true, true],
                [false, true, true],
                [false, true, false],
            ],
            &[
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [true, true, false],
                [true, false, false],
                [false, true, false],
                [false, true, true],
                [true, true, true],
                [false, true, false],
                [true, false, true],
            ],
            &[
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, true, true],
                [false, true, true],
                [true, true, false],
                [false, true, false],
                [false, true, true],
                [true, false, false],
                [true, true, false],
            ],
            &[
                [true, true, true],
                [true, false, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, true],
                [true, true, true],
                [true, false, true],
            ],
            &[
                [false, true, false],
                [true, true, true],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, true, false],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
            ],
            &[
                [true, true, false],
                [false, true, true],
                [true, false, false],
                [false, false, false],
                [true, true, false],
                [false, true, false],
                [true, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, true],
            ],
            &[
                [false, true, false],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [true, true, true],
                [false, true, true],
                [true, true, true],
                [true, true, true],
                [false, false, true],
                [false, true, false],
            ],
            &[
                [true, false, false],
                [true, true, true],
                [false, true, false],
                [true, false, true],
                [false, true, true],
                [false, false, true],
                [false, true, true],
                [true, false, false],
                [true, true, true],
                [true, false, true],
            ],
            &[
                [true, true, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, true, true],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [true, true, false],
                [false, false, true],
            ],
        ],
        negative_traces: vec![
            &[
                [false, true, true],
                [false, false, true],
                [false, true, false],
                [false, false, true],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, false],
            ],
            &[
                [false, true, true],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
            ],
            &[
                [false, true, true],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
            ],
            &[
                [false, true, false],
                [false, false, true],
                [false, true, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, false],
                [false, false, false],
            ],
            &[
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
            ],
            &[
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [true, false, false],
            ],
            &[
                [true, false, false],
                [true, false, false],
                [false, false, true],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
            ],
            &[
                [false, true, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
            ],
            &[
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
            ],
            &[
                [false, true, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
            ],
            &[
                [false, true, false],
                [false, false, true],
                [false, true, false],
                [false, true, true],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, false],
            ],
            &[
                [false, false, false],
                [false, true, true],
                [false, true, true],
                [false, false, false],
                [false, true, false],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [false, false, false],
                [true, false, true],
            ],
            &[
                [false, true, true],
                [false, true, false],
                [false, false, false],
                [true, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, true],
            ],
            &[
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, false],
                [true, false, true],
                [true, false, true],
                [true, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [false, false, false],
                [false, false, false],
                [false, false, false],
                [true, false, true],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [true, false, true],
                [true, false, false],
                [true, false, true],
            ],
            &[
                [true, false, false],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, true],
            ],
            &[
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, false],
                [false, false, true],
                [true, false, false],
                [true, false, false],
                [false, false, false],
                [true, false, true],
            ],
            &[
                [false, true, true],
                [false, true, false],
                [false, true, false],
                [true, false, true],
                [false, false, false],
                [true, false, false],
                [false, false, true],
                [false, false, true],
                [false, false, false],
                [false, false, true],
            ],
        ],
    }
}
