mod too_big_to_handle;

use learn_pltl_fast::*;

fn main() {
    let sample = Sample {
        positive_traces: vec![
            &[
                [false, false],
                [false, false],
                [false, true],
                [false, false],
                [false, true],
            ],
            &[
                [false, true],
                [false, true],
                [false, false],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, false],
                [false, true],
                [false, false],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, false],
                [false, true],
                [false, false],
                [false, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, false],
                [false, true],
                [false, false],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, true],
                [false, false],
            ],
            &[
                [false, true],
                [false, true],
                [false, false],
                [false, true],
                [false, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, false],
                [false, true],
                [false, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, true],
                [false, true],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, false],
                [false, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, false],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, false],
                [false, false],
            ],
            &[
                [false, true],
                [false, false],
                [false, true],
                [false, true],
                [false, false],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, true],
                [false, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, false],
                [false, true],
                [false, false],
            ],
            &[
                [false, true],
                [false, false],
                [false, false],
                [false, true],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, false],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, false],
                [false, false],
            ],
            &[
                [false, true],
                [false, true],
                [false, true],
                [false, true],
                [false, true],
            ],
            &[
                [false, false],
                [false, false],
                [false, true],
                [false, true],
                [false, true],
            ],
            &[
                [false, false],
                [false, false],
                [false, false],
                [false, true],
                [false, false],
            ],
            &[
                [false, false],
                [false, true],
                [false, false],
                [false, true],
                [false, false],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [false, true],
                [false, true],
            ],
        ],
        negative_traces: vec![
            &[
                [false, false],
                [true, true],
                [true, true],
                [false, true],
                [false, false],
            ],
            &[
                [true, false],
                [false, false],
                [false, false],
                [false, false],
                [false, true],
            ],
            &[
                [false, false],
                [false, false],
                [true, false],
                [false, false],
                [false, false],
            ],
            &[
                [true, true],
                [false, false],
                [false, true],
                [true, false],
                [false, false],
            ],
            &[
                [true, false],
                [false, false],
                [true, true],
                [true, true],
                [true, true],
            ],
            &[
                [false, true],
                [true, true],
                [true, false],
                [false, false],
                [true, true],
            ],
            &[
                [false, true],
                [false, false],
                [false, true],
                [true, true],
                [true, false],
            ],
            &[
                [true, true],
                [true, true],
                [false, true],
                [true, false],
                [true, true],
            ],
            &[
                [false, true],
                [false, false],
                [true, true],
                [true, true],
                [false, false],
            ],
            &[
                [true, false],
                [false, true],
                [true, false],
                [true, false],
                [true, false],
            ],
            &[
                [true, true],
                [true, false],
                [false, false],
                [false, true],
                [true, false],
            ],
            &[
                [true, false],
                [false, true],
                [false, true],
                [false, false],
                [false, false],
            ],
            &[
                [false, false],
                [true, false],
                [false, true],
                [true, false],
                [true, true],
            ],
            &[
                [false, true],
                [true, false],
                [false, false],
                [true, false],
                [false, false],
            ],
            &[
                [false, false],
                [true, false],
                [false, true],
                [true, false],
                [true, true],
            ],
            &[
                [false, true],
                [true, true],
                [false, false],
                [true, true],
                [false, false],
            ],
            &[
                [true, true],
                [true, true],
                [true, false],
                [false, false],
                [true, true],
            ],
            &[
                [false, true],
                [true, false],
                [false, true],
                [true, false],
                [true, true],
            ],
            &[
                [true, false],
                [true, false],
                [true, false],
                [true, true],
                [false, false],
            ],
            &[
                [false, true],
                [true, false],
                [false, false],
                [true, true],
                [false, false],
            ],
            &[
                [true, false],
                [false, true],
                [false, true],
                [false, true],
                [false, true],
            ],
            &[
                [false, false],
                [false, true],
                [false, true],
                [true, false],
                [true, true],
            ],
            &[
                [true, false],
                [false, true],
                [true, true],
                [true, true],
                [true, false],
            ],
            &[
                [true, false],
                [false, true],
                [true, true],
                [false, true],
                [true, true],
            ],
            &[
                [false, false],
                [true, true],
                [false, false],
                [false, false],
                [false, true],
            ],
        ],
    };

    println!("Sample:\n{:?}\n", sample);

    println!("Solution:\n{:?}", brute_solve(&sample));
}
